[package]
name = "bevy-typst-textures"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_ecs = "0.16"
bevy_asset = "0.16"
bevy_app = "0.16"
bevy_reflect = "0.16"
typst-as-lib = "=0.14.4"
serde = "1"
derive_more = { version = "1.0.0", features = ["error"] }
zip = {version = "4.2.0", default-features = false, features = [
    "aes-crypto",
    "bzip2",
    "deflate64",
    "deflate",
    "time",
    "zstd",
]}
typst = "0.13.1"
toml = "0.8.19"